version: '3.8'

services:
  youstream:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      invidious:
        condition: service_healthy
      youstream-api:
        condition: service_started

  youstream-api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - POSTGRES_USER=kemal
      - POSTGRES_PASSWORD=kemal
      - POSTGRES_DB=invidious
      - POSTGRES_HOST=postgres
      - INVIDIOUS_URL=http://invidious:3000
    depends_on:
      postgres:
        condition: service_healthy
      invidious:
        condition: service_healthy

  invidious:
    image: quay.io/invidious/invidious:latest
    restart: always
    ports:
      - "3002:3000" # Expose sur 3002 (3001 occup√©)
    volumes:
      - ./config/invidious/config.yml:/invidious/config/config.yml
    environment:
      - INVIDIOUS_INVIDIOUS_COMPANION_PRIVATE_URL=http://invidious-companion:8282/companion
      - INVIDIOUS_INVIDIOUS_COMPANION_TOKEN_PRIVATE_KEY=0123456789abcdef
      # - INVIDIOUS_VISITOR_DATA=CgtvOWc2WlQ5bm1uZyjO9uGdBjIKCgJGUxIEZ3dwBg==

      - INVIDIOUS_HMAC_KEY=0123456789abcdef
      - INVIDIOUS_LOG_LEVEL=debug
    healthcheck:
      test: wget --spider http://127.0.0.1:3000/api/v1/stats || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    dns:
      - 8.8.8.8
    depends_on:
      postgres:
        condition: service_healthy
      invidious-companion:
        condition: service_started

  invidious-companion:
    image: quay.io/invidious/invidious-companion:latest
    restart: always
    ports:
      - "8282:8282"
    environment:
      - RUST_LOG=debug
      - SERVER_SECRET_KEY=0123456789abcdef
      - HMAC_KEY=0123456789abcdef
      # - INVIDIOUS_URL=http://invidious:3000
    dns:
      - 8.8.8.8

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kemal
      - POSTGRES_PASSWORD=kemal
      - POSTGRES_DB=invidious
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kemal -d invidious" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
