db:
  dbname: invidious
  user: kemal
  password: kemal
  host: postgres
  port: 5432

check_tables: true
force_resolve: ipv4
local: true
hmac_key: "0123456789abcdef"
invidious_companion_key: "0123456789abcdef"
cache_annotations: false

# Legacy signature server disabled
signature_server_enabled: false

# Invidious Companion Configuration
invidious_companion:
  - private_url: "http://invidious-companion:8282/companion"
    public_url: "http://localhost:8282/companion"
